### PR TITLE
[gsoc] Created Urllib3Using.py.

### PR DESCRIPTION
**Pull request by sannanansari**
Test file for Urllib3.

What does this PR do?
Urllib3 library.

Why was it initiated? Any relevant Issues?
To test Urllib3 library is relevant for nuitka.

### PR Checklist
- [x] Correct base branch selected? `develop` for new features and bug fixes too. If it's
      part of a hotfix, it will be moved to ``master`` during it.
- [x] All tests still pass. Check the developer manual about ``Running the Tests``. There
      are Travis tests that cover the most important things however, and you are
      welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
No pull request should be against "master", only "develop" branch of Nuitka. And avoid merge commits by doing `git rebase`

**Comment by kayhayen** [comment]
Correct me if I am wrong, but I think your other PR has this in a better form.

**Comment by sannanansari** [comment]
@kayhayen Sorry because my PR is not upto the mark. Since this is my first GSOC and PR I don't have much knowledge about it. Anyway I learn something from this PR.

**Comment by kayhayen** [comment]
@sannanansari Don't worry, keeping branches separate is kind of tough, and I will accept the change through a single PR if you don't mind.

**Pull request closed without merging**
