### PR TITLE
fix: correct the lookup of `command`

### PR DESCRIPTION
**Pull request by TargetLocked**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md)

# What does this PR do?

This PR corrects the lookup behavior of `command`.

When working with #3045 , I find the code here looks a bit strange. The values in `data` here should be results rather than commands, so it makes no sense for me to look for `command` in `data`.

I have not checked logic outside this function, so my view might be wrong.

# Why was it initiated? Any relevant Issues?

No issues related.

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [ ] All tests still pass. Check the Developer Manual about `Running the Tests`. There are GitHub
  Actions tests that cover the most important things however, and you are welcome to rely on those,
  but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
Can you explain some more. Trying it out, just gives me incorrect result `Nuitka-Scons: Compiled 0 C files using ccache.` why you want to do this one?

**Comment by TargetLocked** [comment]
> Can you explain some more. Trying it out, just gives me incorrect result `Nuitka-Scons: Compiled 0 C files using ccache.` why you want to do this one?

This is to me more of a slightly complicated typo rather than a bug fix. The code here means to match `command` and `result` by `pid`. `commands` should map `pid` to `command` while `data` should map `command` to `result`. So `data[commands[pid]]` is a `result` but assigned to `command`, which mixed them up. The reason it worked is the fallback branch `expect KeyError`, making `command` just a unique key of the `result` line, kind of like a hash. Fortunately, we don't use the value of `command` anywhere else, so this is covered up.

The regression is not expected since I thought it would be a simple fix. My apologies for not testing before submitting this PR, I will look into it later. There might be another issue in the related parts.

**Comment by TargetLocked** [comment]
> The reason it worked is the fallback branch `expect KeyError`, making `command` just a unique key of the `result` line, kind of like a hash.

To check this, you may want to try to add some print.

```python
                try:
                    command = data[commands[pid]]
                except KeyError:
                    # It seems writing to the file can be lossy, so we can have results for
                    # unknown commands, but we don't use the command yet anyway, so just
                    # be unique.
                    command = "unknown command leading to " + line
                    scons_logger.warning("fallback")
                else:
                    scons_logger.warning("no fallback")
```

My results show that all lookups fall back.

**Comment by TargetLocked** [comment]
Anyway, the original version works well and is expected to work well as long as we are not going to do something with the value of `command` in the future. If you think such a fix is not necessary, feel free to close this. 😉

**Pull request closed without merging**
