### PR TITLE
WIP: distutils: Use shortest package name as base

### PR DESCRIPTION
**Pull request by jayvdb**
Related to https://github.com/Nuitka/Nuitka/issues/527

### CODE REVIEW

**Comment by jayvdb** [comment]
Very likely this should be improved by splitting the names on `.` and `/`, deps eliminated, and then returning the first top level package name.

It doesnt solve the problem of multiple top-level packages, but there are not many of those.

**Comment by kayhayen** [comment]
There is an issue, where I would like to make Nuitka use `libnuitka` for the static parts. Right now, it is not issuing multiple commands, because most often, one package is always used first, and the second package is more of a slave package, and that kind of limits me.

For repeated compilation, relying on `ccache` for shared code is relatively indirect, and not always working. I intend to do that for the next release cycle.

However, in the mean time, we could in fact, for these rare cases, just duplicate and produce multiple extension modules for now. Inclusion of all in one, will be a hack and show limitations at one or the other instance.

**Comment by kayhayen** [comment]
Also, I think, `something.b`, `something`, `another`, maybe still should be resolved to `something` if we maintain the single top level stuff.

More like removing all sub-packages of packages that are also in the list, before taking the first one, that I would feel might work more often. I do believe, people put the namesake package first, even if not always first. Can you cite, which ones triggered you here? @jayvdb

**Comment by jayvdb** [comment]
All packages using pbr have the modules in the packages in random order.  See https://github.com/Nuitka/Nuitka/issues/527

**Comment by kayhayen** [comment]
This has become obsolete, because of #572 removing the need to select a main package, but instead compiling multiple top level packages as necessary. Therefore, this workaround is no longer useful

**Pull request closed without merging**
