### PR TITLE
Jorj

### PR DESCRIPTION
**Pull request by JorjMcKie**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md

### PR Checklist
- [ ] Correct base branch selected? `develop` for new features and bug fixes too. If it's
      part of a hotfix, it will be moved to ``master`` during it.
- [ ] All tests still pass. Check the developer manual about ``Running the Tests``. There
      are Travis tests that cover the most important things however, and you are
      welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
Treasure trove. :-)

I will look into picking from this over the weekend, and potentially ask questions.

**Comment by JorjMcKie** [comment]
Danke für die Blumen 😊
Based on the insight from yesterday evening (as mentioned on gitter), there will be changes to some of those:

  *   ImplicitImportsPlugin.py
  *   GeventPlugin.py

Jorj

________________________________
Von: Kay Hayen <notifications@github.com>
Gesendet: Friday, May 10, 2019 7:19:24 AM
An: Nuitka/Nuitka
Cc: Jorj X. McKie; Author
Betreff: Re: [Nuitka/Nuitka] Jorj (#381)


Treasure trove. :-)

I will look into picking from this over the weekend, and potentially ask questions.

**Comment by JorjMcKie** [comment]
My today's change of the torch plugin includes support of this under Linux.
Torch is another example for packages with a very different structure between their platform versions.
I would not be surprised, if even more adjustments will be required for these large packages in the future, because it is very hard to achieve coverage with whatever test scripts.

**Comment by JorjMcKie** [comment]
@kayhayen 
As announced, I am leaving tensorflow and friends uncompiled ("bytecode").
This decision is made in the tensorflow plugin - not in ``ImplicitPlugins.py``. The reason being, that not only tensorflow itself is affected, but also a couple of other packages. I imagine, that we do not want to take this decision for all of those, but only in combination with tensorflow - for the time being.

**Comment by kayhayen** [comment]
I am merging this timefrom https://github.com/JorjMcKie/Nuitka.git but I think you ought to directly push into https://github.com/Nuitka/Nuitka.git in the future, and then create a pull request to develop. Seems @deajan managed that. I have no clue how to do it, but I will try and figure out, and write a guide.

In terms of modifications, I am having very harmless merge conflicts resolved (merge tool did it automatically it seems). Once I convinced myself that was proper (sometimes the automatic merge resolution does create stuff that won't even run), I will let you know. For now I am pushing the rebase onto factory (which will also become a pre-release) got Nuitka.git jorj branch, OK? But beware, it may not yet be good. But it probably could be a good base for you to continue on.

It got all my changes except the `--dependency-tool` change which I meant to actually test before making it general default.

**Comment by kayhayen** [comment]
Ok, I merged stuff, and it's on factory now, but probably do not just yet jump on it. The commits have weak commit messages, I will elaborate more.

I think the scan of the standard plugin dir is a good idea. However, I was wondering if it will not break packaging and the reflection test, certainly things I can adapt. Also it seems that user plugins and standard plugins have different scan code. We should probably make a "best of" there.

My private CI is going to churn on these now, and I am hoping to make a pre-release with your your stuff soon. In the future we have that public CI machine from donated money where I will setup a Buildbot for general use. This will e.g. attempt packaging and standalone, and CPython test suites, etc. for you and the students to not have to wait on my private CI after me manually merging to my own stuff in turns.

I will leave this open, until I think you should rebase. If you make new commits, no problem, I get notified by Github and will include them as well. There is no change that you need I think. And yes, indeed the automatic git merge added imports from standard plugins that are now obsolete. :)

**Comment by kayhayen** [comment]
Hello Jorj,

hope you are fine. I was having issues with Python2.6, giving this warning:

> ... /nuitka/plugins/standard/PySidePyQtPlugin.py:10: RuntimeWarning: Parent module 'nuitka.plugins.standard' not found while handling absolute import

I have no idea why the user plugin code doesn't get this. Very probably it does, but nobody notices, surely not my Buildbot. Every import of every plugin gets it.

When googling it, I found the following advice, to simply use: `pkg_util.iter_modules` see https://docs.python.org/2/library/pkgutil.html

That should be simpler then what we do so far and it rings a bell, because I have or was in the process of adding support for compiled modules and this. As a bonus, this also can work with compiled modules and needs no change. So of course we go with that. I will try and change the code in this way if you agree.

**Comment by JorjMcKie** [comment]
Hello Kay,
Of course!
Looking forward to a more elegant solution!
Best,
Kirk

BTW, I hate whoever is responsible for this internet mess!!!

Von meinem iPhone gesendet

**Comment by kayhayen** [comment]
Besides, we didn't yet put tensorflow as unworthy, did we? Because that may make total sense.

**Comment by kayhayen** [comment]
Bad internet is no fun, indeed. But it can give you focus for the time when it's available. You probably still got the better weather as an upside. Hard to ruin that.

**Comment by JorjMcKie** [comment]
> Bad internet is no fun, indeed. But it can give you focus for the time when it's available. You probably still got the better weather as an upside. Hard to ruin that.

Right, but they probably would do that too, if they could ...

**Comment by JorjMcKie** [comment]
> 
> 
> Besides, we didn't yet put tensorflow as unworthy, did we? Because that may make total sense.

In an effort to decrease compile time as much as possible, I am activating ``bytecode`` in the plugin jointly for not only `tensorflow`, but also `sklearn`, `matplotlib` and more. The others should still be compiled if not used together with tensorflow.

**Comment by kayhayen** [comment]
I didn't check that plugin codes too properly it seems. But good point.

I have just release the state of the PR.

Please re-open a new one, and try to push into the org repo instead. In fact, I would recommend to make the other unavailable. Do `git remote origin set-url git@github.com:Nuitka/Nuitka.git` and enjoy, just avoid pushing directly on develop and master. :)

Yours,
Kay

**Pull request closed without merging**
