### PR TITLE
Standalone: Added support to  'eventlet' package

### PR DESCRIPTION
**Pull request by interseba5**
# What does this PR do?
This pull request add support to the eventlet package

# Why was it initiated? Any relevant Issues?
This pull request solves issue #576

### CODE REVIEW

**Comment by kayhayen** [comment]
You are duplicating internal dependencies:

```
- module-name: 'dns.rdtypes'
  implicit-imports:
    - depends:
        - '.IN.A'
        - '.CH.A'
```

I therefore think, two of these could be removed therefore. Will you do it, I can do it after merge too, this is the kind of thing, I am going to put into a hotfix anyway.

**Comment by interseba5** [comment]
Ok, i fix this

**Comment by interseba5** [comment]
Fixed it, i merged the implicit import of eventlet.patcher with the implicit import of dns.rdtypes

**Comment by kayhayen** [comment]
Ok, I am going to merge that.

**Comment by kayhayen** [comment]
Manually merged this to factory, to go into the next hotfix 1.7.4 once it's made.

**Comment by interseba5** [comment]
Great. If in the future you find other issue of missing dependencies i can help with that. I'm on the discord channel with the same name

**Comment by kayhayen** [comment]
@interseba5 I will get back to that shortly :)

**Pull request closed without merging**
