### PR TITLE
PyPI Standalone Tests

### PR DESCRIPTION
**Pull request by tommyli3318**
# What does this PR do?
Creates standalone tests for PyPI packages

# Why was it initiated? Any relevant Issues?
GSoC2019

# PR Checklist

- [x] Correct base branch selected? `develop` for new features and bug fixes too.
      If it's part of a hotfix, it will be moved to `master` during it.
- [x] All tests still pass. Check the developer manual about `Running the Tests`.
      There are Travis tests that cover the most important things however, and you
      are welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
This will be merged once we have the self hosted runners available.

**Comment by jayvdb** [comment]
I would love to see this merged so I can run these on the openSUSE builds.  Can they be disabled by default so they dont effect the github CI?  I am usually only a few releases behind, so failures will get noticed reasonably quickly.

**Comment by kayhayen** [comment]
@jayvdb going to do that then

**Comment by kayhayen** [comment]
I am going to salvage these into Nuitka-Watch where appropiate.

**Comment by kayhayen** [comment]
I manually extracted all things worth using already, we got a different approach with Nuitka-Watch now.

**Pull request closed without merging**
