### PR TITLE
Qt theme for windows

### PR DESCRIPTION
**Pull request by katant**
Recreation of https://github.com/Nuitka/Nuitka/pull/256

Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md

### PR Checklist
- [ ] Correct base branch selected? `develop` for new features and bug fixes too. If it's
      part of a hotfix, it will be moved to ``master`` during it.
- [ ] All tests still pass. Check the developer manual about ``Running the Tests``. There
      are Travis tests that cover the most important things however, and you are
      welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
So it seems "all" and "sensible,styles" should already work for you, can you try `--enable-plugin=qt-plugins=sensible,styles` and see if that does it without the code change? That would leave us with answering if including styles would be sensible or not. 

Does your application pick a style (how), or is this about avoiding a fallback to unstyled that is very ugly, if I recall it correctly?

**Comment by redstoneleo** [comment]
I tried the command with [PyQt5WithPIL.py](https://gist.github.com/redstoneleo/fd260e89701912bb22b0533224d041fe)
`nuitka --standalone --mingw64 --remove-output --enable-plugin=qt-plugins=sensible,styles  PyQt5WithPIL.py --show-progress`
It solved the problem ! I think the meaning of `qt-plugins=sensible,styles` should be explained  in the documentation.

**Comment by kayhayen** [comment]
Hello there,

>
> It solved the problem ! I think the meaning of qt-plugins=sensible,styles
> should be explained in the documentation.
>

I think it should just be part of "sensible", which is the default. I still
need to check out how large an effect it is. The `ImportError` and Qt
plugin discovery problem is something I am going to look into later. I have
access to a Windows machine, but too low on time right now.

But thanks on persisting in reporting on this issue, it seems easy now.

Yours,
Kay

>

**Comment by kayhayen** [comment]
To merge this change, I would need to know what kind of impact including styles has one Windows and Linux in terms of distribution size, otherwise this could easily lead to creep in dependencies on KDE, Gnome, what not, and even for styles on Windows, how many are there, which effect does it have, do we want to include only one?

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Pull request closed without merging**
