### PR TITLE
Existing cache dir fix

### PR DESCRIPTION
**Pull request by deajan**
### What does this PR do?

Fix a small issue when half of the dependency cache path exists, hence makedirs will try to create it all and may fail.

### Why was it initiated? Any relevant Issues?

No relevant issues, just less annoying when playing with dependency cache files.

### PR Checklist
- [X] Correct base branch selected? `develop` for new fetures and bug fixes too. If it's
      part of a hotfix, it will be moved to ``master`` during it.
- [X] All tests still pass. Check the developer manual about ``Running the Tests``. There
      are Travis tests that cover the most important things however, and you are
      welcome to rely on those, but they might not cover enough.
- [X] Ideally new features or fixed regressions ought to be covered via new tests.
     Not applicable
- [X] Ideally new or changed features have documentation updates.
     Not applicable

### CODE REVIEW

**Comment by kayhayen** [comment]
I am confused, is it not that `os.makedirs` promises exactly that it creates intermediate directories? Can you provide an `rm` command to reproduce? I noticed something in the past I think, hence the top level `isdir()` check. Are you saying it will create stuff, and then exit with `OSError` when parts exist?

And if that is the case, I think it might happen a lot with multiple cache directories used.

**Comment by kayhayen** [comment]
```
from nuitka.utils.FileOperations import makePath

makePath("deep/down/there")
makePath("deep/near/there")
```

But this works, does it not? There is that `os.path.isdir()` check there. Which of course would not catch on for files, but that would be weird anyway. Did not try on Windows, is it different there?

Yours,
Kay

**Comment by deajan** [comment]
Your example works the same on Windows.
Yet, my Nuitka compilations triggers OSError 17 randomly in that part.
I have a hard time trying to find the reason and a reproductible code.
Maybe some concurrent issues when cache dirs are created by threads at the same time ?

**Comment by kayhayen** [comment]
You are very likely correct, the dependency walker code is running in threads, and 2 of them might find the need to create the cache directory first time.

However, we might do away with that. That threading is just there because dependency walker is so horribly slow, but pefile maybe just isn't? You can set thread count to 1 there I guess to remove that effect for your branch.

Of course, in the light of that, your fix totally makes sense to me now and these kind of stupid races totally make sense.

Some form of `_withLock()` around the call to `makePath` might be missing right now, and maybe a directory existance check, so it's not acquiring the lock if it already exists. That ought to solve it for good.

Yours,
Kay

**Comment by kayhayen** [comment]
Looks good to me, will merge once Travis completed.

**Comment by deajan** [comment]
Could test the whole thing again today, seems to work for me.

**Comment by kayhayen** [comment]
Why did you add @contextmanager to some of the functions though, that should not be necessary, right? Or is it?

**Comment by deajan** [comment]
I do think it's needed to decorate a function that has with / yield statements.
I can be wrong too, being more or less a Python n00b :)

**Comment by phil65** [comment]
only _with_file_Lock() needs the decorator. :)

**Comment by kayhayen** [comment]
I removed the others in a cleanup commit, what surprised me what that it has no effect, but that is actually to be expected. The context manager provides for `__enter__` and `__exit__`, but not not change `__call__` other than wrapping it through a class.

Thanks for clarifying, and sorry for the noise. :)

**Pull request merged**
