### PR TITLE
Plugins: Fix removeDllDependencies

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/Nuitka/Nuitka/issues/2016

### CODE REVIEW

**Comment by kayhayen** [comment]
I see, this was broken in the rewrite of the dependency parser, the call however would not use the return value, so this would not have the intended effect it seems, even if it doesn't crash.

**Comment by jayvdb** [comment]
I'll update `Standalone.py` and see how it goes.

**Comment by jayvdb** [comment]
@kayhayen is this what you had in mind?

**Comment by kayhayen** [comment]
Using set allows the order to change. We should replace it with OrderedSet therefore. Otherwise DLL scanning code becomes indemistic. I once had that before and it can be very annoying for debugging.

**Comment by kayhayen** [comment]
Thanks, this too is going to be in 1.4.1 thanks for your help.

**Pull request merged**
