### PR TITLE
Test to ensure that rsa PyPI package is supported by Nuitka

### PR DESCRIPTION
**Pull request by tab1tha**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md

### PR Checklist
- [x] Correct base branch selected? `develop` for new features and bug fixes too. If it's
      part of a hotfix, it will be moved to ``master`` during it.
- [x] All tests still pass. Check the developer manual about ``Running the Tests``. There
      are Travis tests that cover the most important things however, and you are
      welcome to rely on those, but they might not cover enough.
- [x] Ideally new features or fixed regressions ought to be covered via new tests.
- [x] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by tab1tha** [comment]
@kayhayen please can  you review this PR

**Comment by tab1tha** [comment]
py.test rsaUsing.py (https://pastebin.com/HphdvWPG ): all tests passed
"python rsaUsing.py " and " python -m nuitka --standalone rsaUsing.py " run successfully and the executable is produced as expected

**Comment by kayhayen** [comment]
This looks very confusing in the diff view, can make sure `git rebase origin/develop`, so there is no merge commit, and force push the result? The commits also won't show. And file differences is just everything in the tests folder, which I doubt.

**Comment by tab1tha** [comment]
> This looks very confusing in the diff view, can make sure `git rebase origin/develop`, so there is no merge commit, and force push the result? The commits also won't show. And file differences is just everything in the tests folder, which I doubt.

Thanks a lot for your review. I will clean this up.

**Pull request closed without merging**
