### PR TITLE
follow PyCFunction signatures

### PR DESCRIPTION
**Pull request by lum1n0us**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md)

# What does this PR do?

#3012

# Why was it initiated? Any relevant Issues?

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [ ] All tests still pass. Check the Developer Manual about `Running the Tests`. There are GitHub
  Actions tests that cover the most important things however, and you are welcome to rely on those,
  but they might not cover enough.
- ~~[ ] Ideally new features or fixed regressions ought to be covered via new tests.~~
- ~~[ ] Ideally new or changed features have documentation updates.~~

--- 
- [ ] naming 
- ~~[ ] TODOs in nuitka/build/static_src/InspectPatcher.c~~
- ~~[ ] TODOs in nuitka/build/static_src/MetaPathBasedLoader.c~~
- ~~[ ] TODOs in nuitka/build/static_src/MetaPathBasedLoaderResourceReader.c~~

### CODE REVIEW

**Comment by kayhayen** [comment]
Seems, sometimes I defined even kwds for functions with no arguments, see `Nuitka_ResourceReaderFiles_is_file` which is confusing. I would prefer instead of naming the added value `data` or `value` that it would be called `_unusable` in cases, and where it's missing, name it `args` e.g. `Nuitka_ResourceReaderFiles_exit` takes arguments, but ignores them.

**Comment by lum1n0us** [comment]
There are three arguments in [Nuitka_ResourceReaderFiles_read_text()](https://github.com/Nuitka/Nuitka/blob/develop/nuitka/build/static_src/MetaPathBasedLoaderResourceReaderFiles.c#L170). All are used. What is your opinion if trying to change its signature to `PyObject *(*)(PyObject *, PyObject *)`?

**Comment by lum1n0us** [comment]
> see Nuitka_ResourceReaderFiles_is_file which is confusing. I would prefer instead of naming the added value data or value that it would be called _unusable in cases

Like?

```c
static PyObject *Nuitka_ResourceReaderFiles_is_dir(struct Nuitka_ResourceReaderFilesObject *files, PyObject *args,
                                                   PyObject *kwds) {
```
->
```c
static PyObject *Nuitka_ResourceReaderFiles_is_dir(struct Nuitka_ResourceReaderFilesObject *files, PyObject *args_unusable,
                                                   PyObject *kwds_unusable) {

```

**Comment by kayhayen** [comment]
As it is define `METH_NOARGS` I was thinking it would be different. Nuitka calls those like this:

```PyObject *result = (*method)(self, NULL);```

And the signature you use should only be used when `METH_VARARGS` is set. So either Nuitka makes calling code different there from CPython if you say it through that, or your example is wrong. Unused keyword arguments would work that way though, yes.

**Comment by kayhayen** [comment]
Eh, no, unusable keyword arguments should not exist, which is what your example states.

**Comment by lum1n0us** [comment]
The problem is found by below case(need to compile to .wasm):

``` python
import unittest

# A simple function to illustrate
def parse_int(s):
    return int(s)

class TestConversion(unittest.TestCase):
    # Testing that an exception gets raised
    def test_bad_int(self):
        self.assertRaises(ValueError, parse_int, "N/A")  # <| -- exception HERE!
```

It turns out
1. `parse_int()` throws `ValueError` exception because N/A is invalid
2. `unittest` catches the exception and handles it with `__exit()` of `_AssertRaisesContext`.
3. When `__exit()` uses `traceback.clear_frames()` to clear frames, it goes to `Nuitka_Frame_clear()`.
4. `Nuitka_Frame_clear(struct Nuitka_FrameObject *frame)` doesn't fit the expectation of `PyCFunction` which is `PyObject*(*PyCFunction)(PyObject*, PyObject*).

Since CompiledCellType, CompiledGeneratorType, CompiledFunctionType, CompiledMethodType and CompiledFrameType are widely used, their unsafe function pointer type castings(to PyCFunction) are fixed too.

**Comment by kayhayen** [comment]
This looks good to me so far, let me know when you feel it's complete. I have to say that you ought to remove `(PyCFunction)` casts from Nuitka probably and then you will find them at compile time immediately and all of them. Basically all these casts are creating issues for WASI I guess.

**Comment by lum1n0us** [comment]
Yes. They are.

That's all for the casting PR. It is good to go.

**Pull request merged**
