### PR TITLE
Generating C helper code using Jinja2 and python

### PR DESCRIPTION
**Pull request by riya-17**
hey @kayhayen, I implemented this code and it is working fine yet there are some problems with jinja2 and I am trying to figure that out like there are no global variables in jinja2 which is creating a problem to pass values from jinja2 to python.

one of the solution that i got is creation of dictionary as it always points to its address so no ambiguity is caused but it is also creating a little problem. If you know any relevant solution please do guide me. 

### What does this PR do?
This PR add two given numbers with the help of jinja2. This code is a combination of python and jinja2.

### Why was it initiated? Any relevant Issues?
#283 

### PR Checklist
- [ ] Adding global variable(this can solve almost every problem)

### CODE REVIEW

**Comment by kayhayen** [comment]
I am not sure, what this shows really. Using rendered templates in rendering templates is very unlikely to be useful to us, it it?

I would much prefer also if you aimed at the C code that we described in the trial we made.

**Comment by riya-17** [comment]
@kayhayen if you find this Python code more powerful and readable than I will go with this rather than pure jinja2 code.
I am aiming for that C code and with the help of that C code only I was ale to develop this python code.

**Comment by riya-17** [comment]
@kayhayen are you asking me to use the C code with Python the way it is used in this code https://github.com/iovisor/bcc/blob/12bd958186a8c3bfcf2f74d246b8c06dd20bbc20/tests/python/test_clang.py#L52 ?

**Comment by kayhayen** [comment]
@riya-17 That is not using Jinja, is it? In fact I didn't see any templating there?

I am surprised, you didn't continue on this kind of code, that we mocked up:

```
import jinja2

int_details = {
    "type_name" : "int"
}
float_details = {
    "type_name" : "float"
}
object_details = {
    "type_name" : "object"
}


def toHelperName(type_name):
    return type_name.upper()

def isInt(type_name, operand):
    if type_name == "int":
        return "1"
    elif type_name == "object":
        return "PyInt_Check(%s)" % operand
    else:
        return "0"


add_template_str = r"""
PyObject *BINARY_OPERATION_ADD_{{toHelperName(left.type_name)}}_{{toHelperName(right.type_name)}}(PyObject *operand1, PyObject *operand2) {
    CHECK_OBJECT(operand1);
    CHECK_OBJECT(operand2);

#if PYTHON_VERSION < 300
    // Something similar for Python3 should exist too.
    if ({{isInt(left.type_name, "operand1")}} && {{isInt(right.type_name, "operand2")}}) {
        long a, b, i;

        a = PyInt_AS_LONG(operand1);
        b = PyInt_AS_LONG(operand2);

        i = a + b;

        // Detect overflow, in which case, a "long" object would have to be
        // created, which we won't handle here.
        if (likely(!((i ^ a) < 0 && (i ^ b) < 0))) {
            return PyInt_FromLong(i);
        }
    }
#endif

    binaryfunc slot1 = NULL;
    binaryfunc slot2 = NULL;

    PyTypeObject *type1 = Py_TYPE(operand1);
    PyTypeObject *type2 = Py_TYPE(operand2);

    if (type1->tp_as_number != NULL && NEW_STYLE_NUMBER(operand1)) {
        slot1 = type1->tp_as_number->nb_add;
    }

    if (type1 != type2) {
        if (type2->tp_as_number != NULL && NEW_STYLE_NUMBER(operand2)) {
            slot2 = type2->tp_as_number->nb_add;

            if (slot1 == slot2) {
                slot2 = NULL;
            }
        }
    }

    if (slot1 != NULL) {
        if (slot2 && PyType_IsSubtype(type2, type1)) {
            PyObject *x = slot2(operand1, operand2);

            if (x != Py_NotImplemented) {
                if (unlikely(x == NULL)) {
                    return NULL;
                }

                return x;
            }

            Py_DECREF(x);
            slot2 = NULL;
        }

        PyObject *x = slot1(operand1, operand2);

        if (x != Py_NotImplemented) {
            if (unlikely(x == NULL)) {
                return NULL;
            }

            return x;
        }

        Py_DECREF(x);
    }

    if (slot2 != NULL) {
        PyObject *x = slot2(operand1, operand2);

        if (x != Py_NotImplemented) {
            if (unlikely(x == NULL)) {
                return NULL;
            }

            return x;
        }

        Py_DECREF(x);
    }

#if PYTHON_VERSION < 300
    if (!NEW_STYLE_NUMBER(operand1) || !NEW_STYLE_NUMBER(operand2)) {
        int err = PyNumber_CoerceEx(&operand1, &operand2);

        if (unlikely(err < 0)) {
            return NULL;
        }

        if (err == 0) {
            PyNumberMethods *mv = Py_TYPE(operand1)->tp_as_number;

            if (mv) {
                binaryfunc slot = mv->nb_add;

                if (slot != NULL) {
                    PyObject *x = slot(operand1, operand2);

                    Py_DECREF(operand1);
                    Py_DECREF(operand2);

                    if (unlikely(x == NULL)) {
                        return NULL;
                    }

                    return x;
                }
            }

            // CoerceEx did that
            Py_DECREF(operand1);
            Py_DECREF(operand2);
        }
    }
#endif

    // Special case for "+", also works as sequence concat.
    PySequenceMethods *seq_methods = Py_TYPE(operand1)->tp_as_sequence;

    if (seq_methods && seq_methods->sq_concat) {
        PyObject *result = (*seq_methods->sq_concat)(operand1, operand2);

        if (unlikely(result == NULL)) {
            return NULL;
        }

        return result;
    }

    PyErr_Format(PyExc_TypeError, "unsupported operand type(s) for +: '%s' and '%s'", type1->tp_name, type2->tp_name);

    return NULL;
}
"""

add_template = jinja2.Template(add_template_str)

types = (int_details, float_details, object_details)

for left in types:
    for right in types:
        print(add_template.render(left=left, right=right,
                                  # TODO: Move thoses ones to environment "env"
                                  toHelperName=toHelperName, isInt=isInt))
```

In my mind, the `TODO` item about `env` is crap, those free functions should simply be methods of the type descriptions, that most probably should simply be objects, and then you call `left.isInt()` and go from there.

**Comment by kayhayen** [comment]
Your examples have the disadvantage of using Python code to generate Python code with Jinja2 code, and thus making it very unclear what is what, and being far from the problem that #283 is about.

**Comment by kayhayen** [comment]
If you mean to explore macros, or if statements, etc. I would rather see it applied to this kind of code, because it makes it clear, why it's useful.

I personally think that there may come a point where e.g. macros could be useful. But much like what I said previously, right now I would be hard pressed to understand why. Maybe when you leave `ADD_*` as a completed thing and find that `MUL_*` shares things that are best expressed that way.

I re-new my recommendation to first get something working, then to search for missing features of Jinja2 that we are not using. There is absolutely no problem to re-factor later. And I am highly dubious that different operations will have very much to share.

**Comment by riya-17** [comment]
> 
> 
> @riya-17 That is not using Jinja, is it? In fact I didn't see any templating there?
> 
> I am surprised, you didn't continue on this kind of code, that we mocked up:
> 
> ```
> import jinja2
> 
> int_details = {
>     "type_name" : "int"
> }
> float_details = {
>     "type_name" : "float"
> }
> object_details = {
>     "type_name" : "object"
> }
> 
> 
> def toHelperName(type_name):
>     return type_name.upper()
> 
> def isInt(type_name, operand):
>     if type_name == "int":
>         return "1"
>     elif type_name == "object":
>         return "PyInt_Check(%s)" % operand
>     else:
>         return "0"
> 
> 
> add_template_str = r"""
> PyObject *BINARY_OPERATION_ADD_{{toHelperName(left.type_name)}}_{{toHelperName(right.type_name)}}(PyObject *operand1, PyObject *operand2) {
>     CHECK_OBJECT(operand1);
>     CHECK_OBJECT(operand2);
> 
> #if PYTHON_VERSION < 300
>     // Something similar for Python3 should exist too.
>     if ({{isInt(left.type_name, "operand1")}} && {{isInt(right.type_name, "operand2")}}) {
>         long a, b, i;
> 
>         a = PyInt_AS_LONG(operand1);
>         b = PyInt_AS_LONG(operand2);
> 
>         i = a + b;
> 
>         // Detect overflow, in which case, a "long" object would have to be
>         // created, which we won't handle here.
>         if (likely(!((i ^ a) < 0 && (i ^ b) < 0))) {
>             return PyInt_FromLong(i);
>         }
>     }
> #endif
> 
>     binaryfunc slot1 = NULL;
>     binaryfunc slot2 = NULL;
> 
>     PyTypeObject *type1 = Py_TYPE(operand1);
>     PyTypeObject *type2 = Py_TYPE(operand2);
> 
>     if (type1->tp_as_number != NULL && NEW_STYLE_NUMBER(operand1)) {
>         slot1 = type1->tp_as_number->nb_add;
>     }
> 
>     if (type1 != type2) {
>         if (type2->tp_as_number != NULL && NEW_STYLE_NUMBER(operand2)) {
>             slot2 = type2->tp_as_number->nb_add;
> 
>             if (slot1 == slot2) {
>                 slot2 = NULL;
>             }
>         }
>     }
> 
>     if (slot1 != NULL) {
>         if (slot2 && PyType_IsSubtype(type2, type1)) {
>             PyObject *x = slot2(operand1, operand2);
> 
>             if (x != Py_NotImplemented) {
>                 if (unlikely(x == NULL)) {
>                     return NULL;
>                 }
> 
>                 return x;
>             }
> 
>             Py_DECREF(x);
>             slot2 = NULL;
>         }
> 
>         PyObject *x = slot1(operand1, operand2);
> 
>         if (x != Py_NotImplemented) {
>             if (unlikely(x == NULL)) {
>                 return NULL;
>             }
> 
>             return x;
>         }
> 
>         Py_DECREF(x);
>     }
> 
>     if (slot2 != NULL) {
>         PyObject *x = slot2(operand1, operand2);
> 
>         if (x != Py_NotImplemented) {
>             if (unlikely(x == NULL)) {
>                 return NULL;
>             }
> 
>             return x;
>         }
> 
>         Py_DECREF(x);
>     }
> 
> #if PYTHON_VERSION < 300
>     if (!NEW_STYLE_NUMBER(operand1) || !NEW_STYLE_NUMBER(operand2)) {
>         int err = PyNumber_CoerceEx(&operand1, &operand2);
> 
>         if (unlikely(err < 0)) {
>             return NULL;
>         }
> 
>         if (err == 0) {
>             PyNumberMethods *mv = Py_TYPE(operand1)->tp_as_number;
> 
>             if (mv) {
>                 binaryfunc slot = mv->nb_add;
> 
>                 if (slot != NULL) {
>                     PyObject *x = slot(operand1, operand2);
> 
>                     Py_DECREF(operand1);
>                     Py_DECREF(operand2);
> 
>                     if (unlikely(x == NULL)) {
>                         return NULL;
>                     }
> 
>                     return x;
>                 }
>             }
> 
>             // CoerceEx did that
>             Py_DECREF(operand1);
>             Py_DECREF(operand2);
>         }
>     }
> #endif
> 
>     // Special case for "+", also works as sequence concat.
>     PySequenceMethods *seq_methods = Py_TYPE(operand1)->tp_as_sequence;
> 
>     if (seq_methods && seq_methods->sq_concat) {
>         PyObject *result = (*seq_methods->sq_concat)(operand1, operand2);
> 
>         if (unlikely(result == NULL)) {
>             return NULL;
>         }
> 
>         return result;
>     }
> 
>     PyErr_Format(PyExc_TypeError, "unsupported operand type(s) for +: '%s' and '%s'", type1->tp_name, type2->tp_name);
> 
>     return NULL;
> }
> """
> 
> add_template = jinja2.Template(add_template_str)
> 
> types = (int_details, float_details, object_details)
> 
> for left in types:
>     for right in types:
>         print(add_template.render(left=left, right=right,
>                                   # TODO: Move thoses ones to environment "env"
>                                   toHelperName=toHelperName, isInt=isInt))
> ```
> 
> In my mind, the `TODO` item about `env` is crap, those free functions should simply be methods of the type descriptions, that most probably should simply be objects, and then you call `left.isInt()` and go from there.

@kayhayen Sorry, I got confused regarding the implementation of the code. The approach that I thought I have to follow is to implement this C code exactly using Jinja2 and Python. 

Now what I understand is that I have to develop a code using jinja which generates specialized code. The specialized code that I understood is the one which have different and exact functions for each functionality. 
Example: 
if I have concat two strings than there must be a different and direct function for that .
if I have to add two integers than a function have to be developed which can add values according to data types as we have tried to implement above with int, float and object and various combination of them like int, float or int, long, etc.
If there are comparison operations, <, <=, ==, !=, >=, >, than there should be a function specialised for them with Int data type only as they are only in INT`

Sorry for this misunderstanding this time I would like to ask you to verify whether the outline that I am building Is right or wrong and please correct me?

**Comment by kayhayen** [comment]
@riya-17 Exactly, big relief on my side. :)

When you say "two strings", it means two "PyObject *" known to be strings, e.g. `PyString_Check()` is true for them.

Exactly true, you are supposed to generate code for all possible combinations, or least the important ones. We ought to blacklist the ones that optimization will not allow because they statically raise, e.g. a float object and a list object do not work for "+", they might for "*".

Comparison operations should also be generated for all kinds of combinations and for each of the operators. Currently they exist as manual version for "INT" (Python2 int) only, but that doesn't mean, we do not want them for FLOAT, etc.

It feels as if you re-read the underlying issue, but at least now I understand better what your PRs were aiming at.

**Comment by riya-17** [comment]
@kayhayen yaa, I kind of understood that something is not going right so re-read them and just cleared with you.

**Comment by riya-17** [comment]
> 
> 
> @riya-17 That is not using Jinja, is it? In fact I didn't see any templating there?
> 
> I am surprised, you didn't continue on this kind of code, that we mocked up:
> 
> ```
> import jinja2
> 
> int_details = {
>     "type_name" : "int"
> }
> float_details = {
>     "type_name" : "float"
> }
> object_details = {
>     "type_name" : "object"
> }
> 
> 
> def toHelperName(type_name):
>     return type_name.upper()
> 
> def isInt(type_name, operand):
>     if type_name == "int":
>         return "1"
>     elif type_name == "object":
>         return "PyInt_Check(%s)" % operand
>     else:
>         return "0"
> 
> 
> add_template_str = r"""
> PyObject *BINARY_OPERATION_ADD_{{toHelperName(left.type_name)}}_{{toHelperName(right.type_name)}}(PyObject *operand1, PyObject *operand2) {
>     CHECK_OBJECT(operand1);
>     CHECK_OBJECT(operand2);
> 
> #if PYTHON_VERSION < 300
>     // Something similar for Python3 should exist too.
>     if ({{isInt(left.type_name, "operand1")}} && {{isInt(right.type_name, "operand2")}}) {
>         long a, b, i;
> 
>         a = PyInt_AS_LONG(operand1);
>         b = PyInt_AS_LONG(operand2);
> 
>         i = a + b;
> 
>         // Detect overflow, in which case, a "long" object would have to be
>         // created, which we won't handle here.
>         if (likely(!((i ^ a) < 0 && (i ^ b) < 0))) {
>             return PyInt_FromLong(i);
>         }
>     }
> #endif
> 
>     binaryfunc slot1 = NULL;
>     binaryfunc slot2 = NULL;
> 
>     PyTypeObject *type1 = Py_TYPE(operand1);
>     PyTypeObject *type2 = Py_TYPE(operand2);
> 
>     if (type1->tp_as_number != NULL && NEW_STYLE_NUMBER(operand1)) {
>         slot1 = type1->tp_as_number->nb_add;
>     }
> 
>     if (type1 != type2) {
>         if (type2->tp_as_number != NULL && NEW_STYLE_NUMBER(operand2)) {
>             slot2 = type2->tp_as_number->nb_add;
> 
>             if (slot1 == slot2) {
>                 slot2 = NULL;
>             }
>         }
>     }
> 
>     if (slot1 != NULL) {
>         if (slot2 && PyType_IsSubtype(type2, type1)) {
>             PyObject *x = slot2(operand1, operand2);
> 
>             if (x != Py_NotImplemented) {
>                 if (unlikely(x == NULL)) {
>                     return NULL;
>                 }
> 
>                 return x;
>             }
> 
>             Py_DECREF(x);
>             slot2 = NULL;
>         }
> 
>         PyObject *x = slot1(operand1, operand2);
> 
>         if (x != Py_NotImplemented) {
>             if (unlikely(x == NULL)) {
>                 return NULL;
>             }
> 
>             return x;
>         }
> 
>         Py_DECREF(x);
>     }
> 
>     if (slot2 != NULL) {
>         PyObject *x = slot2(operand1, operand2);
> 
>         if (x != Py_NotImplemented) {
>             if (unlikely(x == NULL)) {
>                 return NULL;
>             }
> 
>             return x;
>         }
> 
>         Py_DECREF(x);
>     }
> 
> #if PYTHON_VERSION < 300
>     if (!NEW_STYLE_NUMBER(operand1) || !NEW_STYLE_NUMBER(operand2)) {
>         int err = PyNumber_CoerceEx(&operand1, &operand2);
> 
>         if (unlikely(err < 0)) {
>             return NULL;
>         }
> 
>         if (err == 0) {
>             PyNumberMethods *mv = Py_TYPE(operand1)->tp_as_number;
> 
>             if (mv) {
>                 binaryfunc slot = mv->nb_add;
> 
>                 if (slot != NULL) {
>                     PyObject *x = slot(operand1, operand2);
> 
>                     Py_DECREF(operand1);
>                     Py_DECREF(operand2);
> 
>                     if (unlikely(x == NULL)) {
>                         return NULL;
>                     }
> 
>                     return x;
>                 }
>             }
> 
>             // CoerceEx did that
>             Py_DECREF(operand1);
>             Py_DECREF(operand2);
>         }
>     }
> #endif
> 
>     // Special case for "+", also works as sequence concat.
>     PySequenceMethods *seq_methods = Py_TYPE(operand1)->tp_as_sequence;
> 
>     if (seq_methods && seq_methods->sq_concat) {
>         PyObject *result = (*seq_methods->sq_concat)(operand1, operand2);
> 
>         if (unlikely(result == NULL)) {
>             return NULL;
>         }
> 
>         return result;
>     }
> 
>     PyErr_Format(PyExc_TypeError, "unsupported operand type(s) for +: '%s' and '%s'", type1->tp_name, type2->tp_name);
> 
>     return NULL;
> }
> """
> 
> add_template = jinja2.Template(add_template_str)
> 
> types = (int_details, float_details, object_details)
> 
> for left in types:
>     for right in types:
>         print(add_template.render(left=left, right=right,
>                                   # TODO: Move thoses ones to environment "env"
>                                   toHelperName=toHelperName, isInt=isInt))
> ```
> 
> In my mind, the `TODO` item about `env` is crap, those free functions should simply be methods of the type descriptions, that most probably should simply be objects, and then you call `left.isInt()` and go from there.

@kayhayen I am left with one more doubt that the code that we mocked up was in python and jinja, the code that have to be implemented within r""" """ should be implemented in python right?
Means overall I wanted to ask that is there a roll of C language in these functions implementation or only jinja2 and python?

**Comment by riya-17** [comment]
Hey @kayhayen can you look into this once and clear this doubt as well :)

**Comment by kayhayen** [comment]
@riya-17 You are supposed to generate *only* C code. You are supposed to use Python and Jinja2 to do that. Inside the templates, I expect therefore C code template, expanded using Jinja2.

**Comment by riya-17** [comment]
@kayhayen So the code inside r""" code """ needs to be in C language and handled with the help of template. right?

**Comment by riya-17** [comment]
@kayhayen Sorry for these many questions but this time I don't want to misunderstand anything due to which I am confirming my doubts So that I don't get wrong this time and able to produce results soon.

**Comment by kayhayen** [comment]
@riya-17 It's not a problem, but wasn't my comment right before saying that? 

Do you understand, what the template language is? Which one is that?
Do you understand, what the templated language is? Which one is that?
Do you understand, what the glue language is? Which one is that?

In an ideal world, you would figure those answers out. :-)

**Comment by riya-17** [comment]
@kayhayen Thank you :) I will figure out :)

**Pull request closed without merging**
