### PR TITLE
Update TransformersPlugin.py

### PR DESCRIPTION
**Pull request by KRRT7**
adds missing models

### CODE REVIEW

**Comment by KevinRodriguez777** [comment]
closes #2407

**Comment by kayhayen** [comment]
Looks good to me, apparently so sorted the items, makes sense, I think this might have been file system sorting from my WSL or so.

**Comment by kayhayen** [comment]
My only concern is that bitsandbytes changed their wheel packaging for a version, if possible, I would love to figure out the version that did it. Let me try, it's easy enough with --list-package-dlls and some bisecting.

**Comment by kayhayen** [comment]
I had manually merged this one and then forgotten to close it.

**Pull request closed without merging**
