### PR TITLE
Fix index out of range while finding module.

### PR DESCRIPTION
**Pull request by leng-yue**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md)

# What does this PR do?
While `is not None` doesn't check whether the list is empty, it may raise `IndexError: list index out of range`.

# Why was it initiated? Any relevant Issues?
While I try to build use nuitka, I meet this bug.

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch. 
- [x] All tests still pass. Check the developer manual about `Running the Tests`.
      There are Github Actions tests that cover the most important
      things however, and you are welcome to rely on those, but they might not
      cover enough.

Since this is just a fix, I don't add new features.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
Can you provide the `.pth` file that caused this, I am confused as to why it happens in the first place.

**Comment by leng-yue** [comment]
Here is an example

```python3
python -m nuitka --follow-imports --plugin-enable=numpy --plugin-enable=torch --no-prefer-source-code --windows-icon-from-ico=favicon.ico --plugin-enable=pylint-warnings --output-dir=./dist --assume-yes-for-downloads --windows-disable-console --plugin-enable=qt-plugins --include-qt-plugins=sensible,styles --include-package=torch  --nofollow-import-to=cython main.py --standalone --plugin-enable=multiprocessing --user-plugin=./scripts/vmp-plugin.py
```

This error only occurs after I add `--user-plugin=./scripts/vmp-plugin.py`.    

vmp-plugin.py
```python3
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import os
import subprocess
import zipfile
import tempfile
import requests
from nuitka import Options
from nuitka.plugins.PluginBase import NuitkaPluginBase

TEMPLATE = """CONSTATNT CAN'T SHARE"""


class VMPPlugin(NuitkaPluginBase):
    plugin_name = "vmp"

    def __init__(self):
        if not self.isRelevant(): return

        self.tmp_dir = tempfile.TemporaryDirectory()
        self.vmp = self.tmp_dir.name

        print("-------- Downloading VMP --------")
        data = requests.get("PRIVATE URL").content
        open(os.path.join(self.vmp, "vmp.zip"), "wb").write(data)
        with zipfile.ZipFile(os.path.join(self.vmp, "vmp.zip"), 'r') as zip_ref:
            zip_ref.extractall(self.vmp)

    @classmethod
    def isRelevant(cls):
        """This method is called one time only to check, whether the plugin might make sense at all.
        Returns:
            True if this is a standalone, else False.
        """
        return Options.isStandaloneMode() and Options.isWin32Windows()

    def onStandaloneDistributionFinished(self, dist_dir: str):
        if not self.isRelevant() or dist_dir.endswith(".exe"): return

        vmp_config = os.path.join(dist_dir, "main.exe.vmp")
        open(vmp_config, "w").write(TEMPLATE)
        print("-------- Executing VMP --------")
        vmp_exe = os.path.join(self.vmp, "VMProtect_Con.exe")
        subprocess.run([vmp_exe, "main.exe.vmp", "main.exe"], cwd=dist_dir)
        os.unlink(vmp_config)
```

It's weird that this plugin works fine in one project without editing `is not None`, but it doesn't work for another project...
I am not sure why this bug happens. But after I remove `is not None`, it works fine.

**Comment by kayhayen** [comment]
It must be something in the VMP that you didn't share. I will need a reproducer. Look out for `.pth` files it creates in your Python file, and then provide the contents. If you cannot do that, I am afraid there is no way to help.

The fix is on the wrong end, obviously the `.pth` file is parsed wrongly, and rather than just ignoring that, I would like to fix it at the root cause, and not at the symptom.

**Comment by kayhayen** [comment]
Also a pointer on what VMP would be nice, if possible so I can judge if this is something for Nuitka commercial: https://nuitka.net/pages/commercial.html

**Comment by leng-yue** [comment]
Thanks for your notification, since I already used VMP in other non-python applications, I didn't find out that Nuitka's commercial version has code protection before. My team will consider it now since VMP can't protect the program well.   

Also, I am looking forward to uploading the ".pth" file, but I don't know what it is. Does nuitka have a guide line to find the ".pth" file?

**Comment by kayhayen** [comment]
@leng-yue it finds it in the `site-packages` folder, this is the code that looks out for them:

```
def getLoadedPackages():
    """Extract packages with no __file__, i.e. they got added manually.

    They are frequently created with "*.pth" files that then check for the
    "__init__.py" to exist, and when it doesn't, then they create during the
    loading of "site.py" an package with "__path__" set.
    """

    for module_name, module in sys.modules.items():
        if not hasattr(module, "__path__"):
            continue

        if hasattr(module, "__file__"):
            continue

        yield module_name, module
```

**Comment by leng-yue** [comment]
Result of getLoadedPackages()
```python3
[('win32com.gen_py', <module 'win32com.gen_py'>), ('urllib3.packages.six.moves', <module 'urllib3.packages.six.moves' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), ('urllib3.pa
ckages.six.moves.urllib', <module 'urllib3.packages.six.moves.urllib' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), ('requests.packages.urllib3.packages.six.moves', <module 'ur
llib3.packages.six.moves' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), ('requests.packages.urllib3.packages.six.moves.urllib', <module 'urllib3.packages.six.moves.urllib' (<ur
llib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), ('six.moves', <module 'six.moves' (<six._SixMetaPathImporter object at 0x00000219DEA88E20>)>)]
```

Full exception
```
urllib3.exceptions
-> from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\ProgramData\\Miniconda3\\envs\\trainer\\lib\\site-packages\\urllib3\\exceptions.py', 'module_name': <ModuleName
 urllib3.exceptions>, 'code_flags': ''}>'.
PASS 1:  49%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                              | 563/1155T
raceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\__main__.py", line 185, in <module>
    main()
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\__main__.py", line 171, in main
    MainControl.main()
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\MainControl.py", line 692, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\MainControl.py", line 161, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\Optimization.py", line 379, in optimize
    finished = makeOptimizationPass()
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\Optimization.py", line 325, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\Optimization.py", line 220, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\Optimization.py", line 120, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 530, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\AssignNodes.py", line 275, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 539, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1182, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 539, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1131, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\ImportNodes.py", line 606, in computeExpression
    self._attemptRecursion(
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\nodes\ImportNodes.py", line 533, in _attemptRecursion
    module_package, module_filename, _finding = findModule(
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\importing\Importing.py", line 256, in findModule
    module_filename = _findModule(module_name=full_name)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\importing\Importing.py", line 608, in _findModule
    module_search_cache[key] = _findModule2(module_name)
  File "C:\ProgramData\Miniconda3\envs\trainer\lib\site-packages\nuitka\importing\Importing.py", line 628, in _findModule2
    return preloaded_path[0]
IndexError: list index out of range
```
I also tested in virtualenv and pure python, and I got the same error.

**Comment by leng-yue** [comment]
Here is *.pth files I found in site-packages

[Google Drive](https://drive.google.com/drive/folders/1OFoBfP5PRBZj7a4OiR0kZs3He-PZEkZK?usp=sharing)

**Comment by leng-yue** [comment]
I solved this problem after I remove the `import requests` from my plugin.   
I hope this information can help you.

**Comment by kayhayen** [comment]
The `distutils-precedence.pth` is doing something non-standard. It seems without the path to the code, Nuitka will not be able to include its effect in the compilation. I will see to try and add warnings and or traces for unusual stuff, so we can see what is causing the issue.

**Comment by leng-yue** [comment]
I reproduce this bug with a minimize example
```
python -m nuitka --version

0.6.14.6
Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Executable: C:\ProgramData\Miniconda3\envs\pythonProject\python.exe
OS: Windows
Arch: x86_64
```


```shell
python -m nuitka --follow-imports --no-prefer-source-code --plugin-enable=pylint-warnings --output-dir=./dist --assume-yes-for-downloads --user-plugin=./scripts/vmp-plugin.py main.py --standalone
```
./scripts/vmp-plugin.py
```python3
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import requests
from nuitka import Options
from nuitka.plugins.PluginBase import NuitkaPluginBase


class VMPPlugin(NuitkaPluginBase):
    plugin_name = "vmp"

    def __init__(self):
        if not self.isRelevant(): return
        requests.get("https://google.com")

    @classmethod
    def isRelevant(cls):
        """This method is called one time only to check, whether the plugin might make sense at all.
        Returns:
            True if this is a standalone, else False.
        """
        return Options.isStandaloneMode() and Options.isWin32Windows()

    def onStandaloneDistributionFinished(self, dist_dir: str):
        if not self.isRelevant() or dist_dir.endswith(".exe"): return
```

./scripts/main.py
```python3
import requests

if __name__ == '__main__':
    requests.get("https://google.com")

```

**Comment by kayhayen** [comment]
@leng-yue thanks for proactively providing the traces, this is very helpful. I formatted it a bit for my reference:

```
[
    ('win32com.gen_py', <module 'win32com.gen_py'>), 
    ('urllib3.packages.six.moves', <module 'urllib3.packages.six.moves' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), 
    ('urllib3.packages.six.moves.urllib', <module 'urllib3.packages.six.moves.urllib' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), 
    ('requests.packages.urllib3.packages.six.moves', <module 'urllib3.packages.six.moves' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), 
    ('requests.packages.urllib3.packages.six.moves.urllib', <module 'urllib3.packages.six.moves.urllib' (<urllib3.packages.six._SixMetaPathImporter object at 0x00000219DEB50E20>)>), 
    ('six.moves', <module 'six.moves' (<six._SixMetaPathImporter object at 0x00000219DEA88E20>)>)
]
```

The win32 is a typical one and going to be dealt with a new anti-bloat plugin that I started. The trouble maker are the ones from `urllib3.packages.six._SixMetaPathImporter`. If six is used locally or from pkg_resources is very Python installation specific, but it is easily explained, that these modules have no file to back them up.

And they are like this:

```
>>> import urllib3.packages.six.moves.urllib
>>> urllib3.packages.six.moves.urllib.__path__
[]
```

So they don't really have any package search impact by themselves. I am fixing this in the function I quoted, by checking the __path__ for non-emptiness.

**Comment by kayhayen** [comment]
As an aside, and something which I not pushing enough, possibly because some virtualenv do not work without it, but if you can, use the `--python-flag=-S` which will not load `.pth` files at all, they often only provide bloat for packages not even used. Expect a fix soon on factory branch.

**Comment by kayhayen** [comment]
So, on the factory branch, I pushed a comparable fix: https://nuitka.net/doc/factory.html

It avoids them where they are detected, and is equally effective to your workaround.

**Comment by leng-yue** [comment]
Thanks a lot!

**Pull request closed without merging**
