### PR TITLE
follow getter and setter signatures

### PR DESCRIPTION
**Pull request by lum1n0us**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md)

# What does this PR do?

Let some functions of *CompiledXXXType.c* in *nuitka/build/static_src* follow the signatures of getter and setter.
 
# Why was it initiated? Any relevant Issues?

#3012 

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [x] All tests still pass. Check the Developer Manual about `Running the Tests`. There are GitHub
  Actions tests that cover the most important things however, and you are welcome to rely on those,
  but they might not cover enough.
- ~~[] Ideally new features or fixed regressions ought to be covered via new tests~~
- ~~[] Ideally new or changed features have documentation updates~~

---

- [x] CompiledAsyncgenType.c
- [x] CompiledCellType.c
- ~~[ ] CompiledCodeHelpers.c~~
- [x] CompiledCoroutineType.c
- [x] CompiledFrameType.c
- [x] CompiledFunctionType.c
- [x] CompiledGeneratorType.c
- ~~[ ] CompiledGeneratorTypeUncompiledIntegration.c~~
- [x] CompiledMethodType.c

### CODE REVIEW

**Comment by kayhayen** [comment]
Very nice, I see you made a list of files to go over with, great job. I will merge once you tell me.

**Comment by lum1n0us** [comment]
@kayhayen The PR is ready for review. Thanks

**Review by kayhayen — APPROVED** [review]
The only thing I would love to see is the removal of the `getter` and `setter` casts, but that is something I can do myself easily. Thanks for your work here.

**Comment by kayhayen** [comment]
LLVM apt source has pulled v19 of clang-format and its not come back for a while now, otherwise it's good

**Comment by lum1n0us** [comment]
I've create https://github.com/Nuitka/Nuitka/pull/3029 for `PyCFunction` function pointers casting. There are some functions have more arguments(3) than definition(2). Need your suggestions to handle them.

**Comment by kayhayen** [comment]
So, I am going to merge this one once it completes the CI run which it ought to now, not sure if it needs a rebase for the clang-format-20 usage still, we shall see, but I think I can gladly take it from here.

**Pull request merged**
