### PR TITLE
Updated Backend.scons to add Haiku header path

### PR DESCRIPTION
**Pull request by roired**
This PR adds Python headers path for Haiku operating system.

With the default Backend.scons, there was no way to run Nuitka on Haiku as the existent paths didn't cover the specific paths in the Haiku operating system thus the headers are never found and Nuitka always halts with the "no Python header found" error.

### CODE REVIEW

**Comment by kayhayen** [comment]
Let me know when you had a chance to test it, so we don't have to do it twice.

**Comment by kayhayen** [comment]
I can take care of the autoformat, no problem.

**Comment by kayhayen** [comment]
Thanks for your contribution, I manually merged it to develop branch.

**Comment by roired** [comment]
Good day @kayhayen,

Thanks for the merge. I'll notify the Haiku community about it, I'm sure the python devs will be happy. 

Nonetheless, I still have to carry some testing with bigger projects, that I haven't had time yet to do. My pace is much slower than yours :)
I'll report any issue I may find when I try to bundle a bigger size project on Haiku. I'll try on metal during the holidays (hope so).

Thanks again and Merry Christmas!
Regards,
RR

**Comment by kayhayen** [comment]
@roired that's ok, take your time, but be sure everything you come up with will be welcome

**Pull request closed without merging**
