### PR TITLE
Make Nuitka use the distribution build folder instead of the source files

### PR DESCRIPTION
**Pull request by pyrito**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md)

# What does this PR do?
Makes Nuitka build from the `build` directory instead of the direct source files. Some projects such as versioneer change the composition of certain files during a distribution build. 

# Why was it initiated? Any relevant Issues?
See: #2207 
# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [x] All tests still pass. Check the Developer Manual about `Running the Tests`.
      There are GitHub Actions tests that cover the most important
      things however, and you are welcome to rely on those, but they might not
      cover enough.
- [x] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by pyrito** [comment]
Hi @kayhayen , luckily versioneer.py is self contained source code so there is no need to add any other dependencies. I also truncated it to only have functionality needed to replicate my issue.

**Comment by kayhayen** [comment]
Ah, wow. Can you clarify the license a bit though, I will have to list that for other downstreams.

**Comment by kayhayen** [comment]
Also, tests passing, so I think are good to go with the license question answered, good job!

**Comment by pyrito** [comment]
@kayhayen per the versioneer repo: https://github.com/python-versioneer/python-versioneer, it seems that the license is "License: Public Domain (Unlicense)", so it is effectively in the public domain and thus we don't have to do anything in particular I believe.

**Comment by kayhayen** [comment]
Ok, but lets not be lazy and at least acknowledge it, putting it under Nuitka tests license otherwise, I will do that then on merge.

**Comment by pyrito** [comment]
@kayhayen do you have any more info you can provide about the RecursionError? Do you think it's related to this PR?

**Comment by kayhayen** [comment]
@pyrito I wrote this into the wrong window, sorry for the noise

**Pull request merged**
