### PR TITLE
support `http.cookiejar`.

### PR DESCRIPTION
**Pull request by byehack**
Thanks for your great project.

### CODE REVIEW

**Comment by kayhayen** [comment]
See my comments in #1551 I believe this only happens to work, because `wsgiref` is included for no good reason, and that's going to change again. You probably want to add an option to Nuitka, say `--include-stdlib` that basically disables in `nuitka/importing/StandardLibrary.py` in the function `isStandardLibraryNoAutoInclusionModule`.

**Comment by byehack** [comment]
```
~~~>python -m nuitka --standalone --mingw64 t.py --report=C.xml --include-stdlib
Usage: __main__.py [--module] [--run] [options] main_module.py

__main__.py: error: no such option: --include-stdlib
```

do you mean `--follow-stdlib`?
I tested with that, but still it doesn't include essential stdlib modules.
```
~~~>python -m nuitka --standalone --mingw64 t.py --report=C.xml --follow-stdlib

Nuitka-Options:INFO: Used command line options: --standalone --mingw64 t.py --report=C.xml --follow-stdlib
Nuitka:INFO: Starting Python compilation with Nuitka '0.8rc9' on Python '3.7' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
Nuitka-Scons:INFO: Compiled 18 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 9
Nuitka:INFO: Keeping build directory 't.build'.
Nuitka:INFO: Successfully created 't.dist\\t.exe'.
Nuitka:INFO: Compilation report in file 'C.xml'.
```
here is report:
[C.zip](https://github.com/Nuitka/Nuitka/files/8605375/C.zip)

**Comment by kayhayen** [comment]
No, I mean you implement `--follow-stdlib` in this PR in the way described.

**Comment by kayhayen** [comment]
The crash for PyLint is on me apparently, I will update develop soon with one that works for PRs again. Didn't consider the git command could fail that way.

**Comment by kayhayen** [comment]
Closing, as you the factory branch contains the right dependency, of course you need to attach it to what actually uses it.

**Comment by byehack** [comment]
> of course you need to attach it to what actually uses it.

`--hidden-import` would be good option to attach them.
currently there is no way to import unused module from command line.

**Comment by kayhayen** [comment]
There is not?

**Pull request closed without merging**
