### PR TITLE
remove duplicate VS Code extension recommendation

### PR DESCRIPTION
**Pull request by vpoulailleau**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md)

# What does this PR do?

Remove a duplicate in .vscode/extensions.json.

# Why was it initiated? Any relevant Issues?

No issue, I saw this while reading the file.

# PR Checklist

- [X] Correct base branch selected? `develop` for new features and bug fixes too.
      If it's part of a hotfix, it will be moved to `master` during it.
- [ ] All tests still pass. Check the developer manual about `Running the Tests`.
      There are Travis tests that cover the most important things however, and you
      are welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

No code is really changed here, so the tests were no re-launched.

### CODE REVIEW

**Comment by vpoulailleau** [comment]
Well, for the base branch, it's not clear to me.

As I understand, the PR template contradicts https://github.com/Nuitka/Nuitka/blob/master/CONTRIBUTING.md#submitting-a-pull-request

So I'm not sure I chose the correct base branch.

**Comment by kayhayen** [comment]
I changed the template and doc, with next release, it will point to base everything on `develop` branch, so you are correct.

**Comment by kayhayen** [comment]
Just out of curiousity, what was the symptom of the duplicate, or did you just spot it?

**Comment by vpoulailleau** [comment]
@kayhayen I just spot it, I was curious and wanted to discover new VS Code extensions…

**Pull request merged**
