### PR TITLE
 Specialized C containers for unknown sizes.

### PR DESCRIPTION
**Pull request by sannanansari**
This PR is for creating an `python list` using C.
 #294 Specialized C containers for known constraints.

### CODE REVIEW

**Comment by kayhayen** [comment]
This is missing the API functions that are similar to the list API of CPython as described in the original issue.

The use of an embedded CPython to compare PyList performance and API usage with your replacement. Mind you, it should be near similar API.

**Comment by sannanansari** [comment]
Sorry I am little bit confused about API. According to me API is like  [C example](https://github.com/Nuitka/Nuitka/blob/9797f77c991ff8507ce84cff35f0d35011189940/nuitka/build/static_src/MainProgram.c).
Please you can explain a bit about API like this. And how can I run it. Sorry for my inexperience.

**Comment by kayhayen** [comment]
@sannanansari That is not meant at all, rather something like this from the CPython API:

https://docs.python.org/2/c-api/list.html

As described in the issue #294 what we are looking at, is a similar container that doesn't do C `malloc` but uses a static global buffer. So when the Nuitka static analysis has shown that to be possible, we could have a faster form here, but one that fits into templates. Having a similar API that the C compiler will often inline away allows for easy generation of C code for cases where it can be used and for cases where it can not be used.

**Comment by sannanansari** [comment]
@kayhayen Please you can review it and tell my mistakes. I have write this code with the help of documentation.

**Comment by sannanansari** [comment]
@kayhayen But problem is that it is not running with nuitka-env. It is running with python.

**Comment by kayhayen** [comment]
@sannanansari not running in Nuitka is OK for this exercise, this is foremost about comparing containers that use e.g. PyList, and PyDict, API etc. and ones that do not do that.

You would e.g. create a container that has a similar API, but is as described in the GSoC issue, not doing a malloc, outside of a static pre-allocated buffer. Maybe if you wrap it in a Python function, the Python API and the @sannanansari API, you can compare them with `timeit`, or the ticks with `/misc/run-with-valgrind` (spelling), what you prefer.

That would be your test bed. And then try to squeeze out things with e.g. "created empty/append some/full Iteration only" lists. That seems good stuff.

**Comment by kayhayen** [comment]
That last commit is quite a shocker to me. You copied the bulk of another PR, including unfixed issues, and definitely not good code. And I am unsure how it relates to your task. Previously you seemed to be generating a C extension that could be ran, and that will save your from building hassle, and now you "stole" a failed build system for a main program binary that calls gcc manually, and won't work. Not a goo idea.

**Comment by sannanansari** [comment]
I am using Github Desktop first time. I want to go from `nuitka->develop` to `nuitka->master`. I accidentally press `ok`. It get commited. Sorry for that.

**Comment by kayhayen** [comment]
No problem, what you have there looks like a fair and probably working small extension module to test the PyList performance. Now make another one, which uses an alternative list implementation of yours, that has similar API.

**Comment by kayhayen** [comment]
This is unlikely to be completed at this time.

**Pull request closed without merging**
