### PR TITLE
Various documentation only changes

### PR DESCRIPTION
**Pull request by JorjMcKie**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md

### PR Checklist
- [x] Correct base branch selected? `develop` for new features and bug fixes too. If it's
      part of a hotfix, it will be moved to ``master`` during it.
- [ ] All tests still pass. Check the developer manual about ``Running the Tests``. There
      are Travis tests that cover the most important things however, and you are
      welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
@JorjMcKie I think I merged part of this with the other PR already, you might have to rebase to current develop. :)

**Comment by JorjMcKie** [comment]
damn, it happened again :-(((
sorry about that.

**Comment by kayhayen** [comment]
@JorjMcKie no problem at all, I was actually pretty happy about it. So I merged it in one go, do you want me to split it up, I could do that.

**Comment by JorjMcKie** [comment]
yes, please if you would ...

**Comment by kayhayen** [comment]
So @JorjMcKie thanks for the contribution, I manually merged this as a separate commit. No big deal.

I am not sure how to deal with pull requests myself if you have many things going on in parallel. I wouldn't mind if you had one branch with changes you like, and you doing pull requests when you think some commit stabilized. Like I do with factory, where I will `git commit --fixup` and then when it all seems good, take it all at once, or the parts deemed definitely good, delaying only parts of it.

Having one pull request branch per commit can easily become tedious. Plus such a branch in Nuitka.git, I think we can build packages for them, so much like I do with "factory", you could share the branch, say "jorj" with users. Just thoughts. We can do what we want after all.

But potentially there are tools that solve this, like e.g. you and I have these kinds of branches, and some sort of plugin to git or whatever make branch and PRs for single commits. I am thinking. But juggling with a lot of branches can quickly become annoying Not sure though if such tools can even exist.

**Comment by JorjMcKie** [comment]
ok, got you. Good ideas. I'll think about what the option is.
What I am usually doing is indeed developing stuff on my computer and be very picky using uploads / downloads because of the f*ing internet connection quality I have to endure here. Literally every single bit going over the line is using up my mobile phone saldo  - which is ridiculously cheap here, mind you, but you have to have local currency to buy new data volume, which again is an online activity, for which you have to have enough saldo, etc.
Enough lamento - what I am just saying is, that I indeed am looking for a process that allows making many changes in one shot.

**Pull request closed without merging**
