### PR TITLE
add libmagic support

### LINKED ISSUE #2829: ImportError: failed to find libmagic.
> python -m nuitka --version
```
2.1.6
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Python: Official installer
Nuitka: pip

  > python -m pip freeze
```
Nuitka==2.1.6
python-magic-bin==0.4.14
```
minimal reproducible:
`nuitka --standalone test.py`
```py
# test.py
import magic
```
Output:
```
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\test.dist\test.py", line 1, in <module>
  File "C:\Users\WDAGUtilityAccount\Desktop\test.dist\magic\__init__.py", line 1, in <module magic>
  File "C:\Users\WDAGUtilityAccount\Desktop\test.dist\magic\magic.py", line 189, in <module magic.magic>
ImportError: failed to find libmagic.  Check your installation
```

Manually copying the `magic` module folder in `site-packages` to the `test.dist` folder solves the issue. It seems nuitka is having trouble adding the package to the output folder.

### PR DESCRIPTION
**Pull request by KRRT7**
closes #2829

### CODE REVIEW

**Comment by kayhayen** [comment]
What about the data file `libmagic/magic.mgc` that should probably be added too?

**Comment by KRRT7** [comment]
> What about the data file `libmagic/magic.mgc` that should probably be added too?

i thought it was the file that is used to build the dll, isn't it?

**Comment by KRRT7** [comment]
i ran their tests and it does need the `.mgc` file.

**Comment by MagicalDrizzle** [comment]
> i ran their tests and it does need the `.mgc` file.
you actually do need the mgc file, that's the actual filetype database. my test was simply importing the module so you don't actually need it.

**Comment by MagicalDrizzle** [comment]
> i ran their tests and it does need the `.mgc` file.

yeah you do need it, it's the actual filetype database.
also my apologies for not making the PR sooner, letting you have to make it

**Review by kayhayen — APPROVED** [review]

**Comment by kayhayen** [comment]
Since the merges annotation failed, I will now click merge, immediately force push it away, move it to the factory, and add it to the hotfix 2.2.1 branch I will create soon.

**Pull request merged**
