### PR TITLE
Fix Haiku support

### PR DESCRIPTION
**Pull request by coolcoder613eb**
This patch fixes support for Haiku.

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [ ] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [ ] All tests still pass. Check the Developer Manual about `Running the Tests`.
      There are GitHub Actions tests that cover the most important
      things however, and you are welcome to rely on those, but they might not
      cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
I might even put this in a 1.7 hotfix later

**Comment by coolcoder613eb** [comment]
this does not help for standalone and onefile.

**Comment by kayhayen** [comment]
What does it help with?

**Comment by coolcoder613eb** [comment]
It helps with just nuitka3 test.py

**Comment by kayhayen** [comment]
Ok, if you open an issue and report what happens to you with `--standalone` I will look at it gladly. You probably need to be able to resolve DLL dependencies. I do not know Haiku well enough, but it will probably be all easy enough, and I am willing to support you there.

**Comment by coolcoder613eb** [comment]
https://github.com/Nuitka/Nuitka/issues/2372

**Comment by coolcoder613eb** [comment]
on x86 when i try to  the compiled binary
```
runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.29: Could not resolve symbol '___tls_get_addr'
resolve symbol "___tls_get_addr" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.29: Troubles relocating: Symbol not found
```

**Comment by kayhayen** [comment]
@coolcoder613eb you really need to stop posting below closed issues, I will not see it more than once and definitely not act on it

**Pull request merged**
