### PR TITLE
Termux onefile check command termux-elf-cleaner.

### PR DESCRIPTION
**Pull request by nacho00112**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md)

# What does this PR do?
Make nuitka check for `termux-elf-cleaner` in Termux.
# Why was it initiated? Any relevant Issues?
https://github.com/Nuitka/Nuitka/issues/2341
# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [x] All tests still pass. Check the Developer Manual about `Running the Tests`.
      There are GitHub Actions tests that cover the most important
      things however, and you are welcome to rely on those, but they might not
      cover enough.
- [x] Ideally new features or fixed regressions ought to be covered via new tests.
- [x] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by nacho00112** [comment]
IMG_20230722_120339
IMG_20230722_120204

**Comment by kayhayen** [comment]
I really dislike screenshots a lot personally.

**Review by kayhayen — APPROVED** [review]
Looks good to me, lets see if auto-format has complaints.

**Comment by nacho00112** [comment]
> I really dislike screenshots a lot personally.

Sorry, i'll take it into account

**Comment by kayhayen** [comment]
If there is any way to copy text from your emulator, please do that instead. If that's not really an option, ok. But don't you ssh or adb into a shell from like a desktop?

**Comment by kayhayen** [comment]
I can deal with the line too long, so I merging it and correcting it right after.

**Comment by nacho00112** [comment]
> If there is any way to copy text from your emulator, please do that instead. If that's not really an option, ok. But don't you ssh or adb into a shell from like a desktop?

Yeah there is, i'll use it instead

**Pull request merged**
