### PR TITLE
Handle conflicting DLLs on MacOS

### PR DESCRIPTION
**Pull request by Giannie**
Thank your for contributing to Nuitka!

!! Please check that you select the **develop branch** (details see below link) !!

Before submitting a PR, please review the guidelines:
[Contributing Guidelines](https://github.com/kayhayen/Nuitka/blob/develop/CONTRIBUTING.md)

# What does this PR do?
Handles conflicting DLLs on MacOS by comparing version numbers and keeping the highest

# Why was it initiated? Any relevant Issues?
https://github.com/Nuitka/Nuitka/issues/1608#issuecomment-1160002420

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [ ] All tests still pass. Check the Developer Manual about `Running the Tests`.
      There are GitHub Actions tests that cover the most important
      things however, and you are welcome to rely on those, but they might not
      cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by kayhayen** [comment]
Mabe I am missing something, but this seems useless:

```
    def __lt__(self, other):
        for i in range(max([len(self.vtuple), len(other.vtuple)])):
            try:
                if self.vtuple[i] < other.vtuple[i]:
                    return True
                elif self.vtuple[i] > other.vtuple[i]:
                    return False
            except IndexError:
                return len(self.vtuple) < len(other.vtuple)
        return False
```

A tuple comparison does that too, does it not? I think I will try without this `VersionTuple`...

**Comment by kayhayen** [comment]
I cherry-picked the commit from your repo, strangely that was only one, and you seem to have rebased with no mercy for unrelated changes, but I was able to resolve it. However, I changed a lot about it, as you used no infrastructure of Nuitka for process execution. I also feel the version tuple has no point, but I guess, testing will reveal that. Please have a look, and let me know if it's OK to have your name as author. Still the idea how to do it is your contribution.

**Comment by Giannie** [comment]
Thank you for committing this and checking in with me. I appreciate the author status. I apologies for poor practices, the change was made to solve a rather pressing issue in our project and it is my first time working on Nuitka. For further pull requests I will endeavor to neaten things up!

**Comment by kayhayen** [comment]
Sorry if I made it sound like you were doing anything wrong, you did not, this was fully understood and agreed. I just wanted you to know what I did, because it's rather more, and if it breaks things, your name is on it now. ;-)

**Pull request closed without merging**
