### PR TITLE
handle if standalone or onefile is specified in pyproject

### PR DESCRIPTION
**Pull request by martinmiglio**
# What does this PR do?
This change would allow for standalone or onefile builds using distutils and pyproject.toml.

# Why was it initiated? Any relevant Issues?
Using distutils and pyproject, only module builds were allowed, this extends that functionality.

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [ ] All tests still pass. Check the Developer Manual about `Running the Tests`.
      There are GitHub Actions tests that cover the most important
      things however, and you are welcome to rely on those, but they might not
      cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Comment by martinmiglio** [comment]
This is not necessarily the best way of going about this, but I tried to maintain existing functionality as best as possible. Looking for feedback...

**Comment by kayhayen** [comment]
It's actually completely wrong. The current code determines the top level packages and then compiles them all. It ignores the entry points entirely. Not sure if they exist at that build time already or not. I think wheels create the runners during installation maybe, not sure.

What this code is to do, is to recognize that an entirely different mode of operation is needed. The top level packages are probably what should be included, with `--include-module` or `--include-package` but a onefile or a dist folder is to be included, either as the runner, or to quickly launch the runner.

It's not about just switching out `--module` for `--onefile` or `--standalone`.

**Comment by kayhayen** [comment]
So you gave up, right?

**Comment by martinmiglio** [comment]
It's not something I can take on right now.

**Pull request closed without merging**
