### PR TITLE
Typo in `license_expression` package ID

### PR DESCRIPTION
**Pull request by kdeldycke**
# What does this PR do?

This fix the bad ID for the `license-expression` package introduced in #3033.

# Why was it initiated? Any relevant Issues?

I'd like to apologise, I mixed up my local copies of Nuitka fork and venv, so I pushed my previous #3033 PR with the wrong package ID. 🙇

I triple-checked this PR really fix the issue with `license-expression` package.

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [x] All tests still pass. Check the Developer Manual about `Running the Tests`. There are GitHub
  Actions tests that cover the most important things however, and you are welcome to rely on those,
  but they might not cover enough.
- [x] Ideally new features or fixed regressions ought to be covered via new tests.
- [x] Ideally new or changed features have documentation updates.

### CODE REVIEW

**Review by kayhayen — APPROVED** [review]

**Comment by kayhayen** [comment]
Oops, we should have caught that. The module names have no schema check at all.

**Comment by kayhayen** [comment]
Adding it reveals another issue:

> Nuitka-Tools: Config for module 'license-expression' is using a package name rather than a module name.
> Nuitka-Tools: Config for module 'mozilla-ca' is using a package name rather than a module name.

So that would have been good during your development.

**Review by kayhayen — APPROVED** [review]

**Comment by kdeldycke** [comment]
Thanks again @kayhayen for the fast merge!

**Comment by kayhayen** [comment]
Going out in the next hotfix as well.

**Comment by kayhayen** [comment]
Turns out mozilla-ca is a valid name, but I allow listed this one, and will error out in the future. I am also changing data files to be lists of items like the other types of values already are with that hotfix, so we avoid merge issues with hotfixes that add data files.

**Pull request merged**
